### ISSUE TITLE
[User] Some exception on values returned by the api

### ISSUE THREAD

**Issue by tikismoke** [quentin7b/xee-sdk-python#1]
result of user api call:

> ```
> {
>   "id": xxxx,
>   "role": "dev",
>   "firstName": "xxxxxxx",
>   "lastName": "xxxxxxx",
>   "nickName": null,
>   "gender": "Male",
>   "isLocationEnabled": true,
>   "birthDate": null,
>   "licenseDeliveryDate": null,
>   "creationDate": "2016-08-31T16:32:59Z",
>   "lastUpdateDate": "2016-08-31T16:57:48Z"
> }
> ```

```
Traceback (most recent call last):
  File "xee_exemple.py", line 21, in <module>
    user = xee.get_user(token)
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/sdk.py", line 140, in get_user
    return xee_entities.parse_user(response), None
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/entities.py", line 166, in parse_user
    user['nickname'],
KeyError: 'nickname'
```

Same because birthdate and lcenceDelivery date are not define:

```
Traceback (most recent call last):
  File "xee_exemple.py", line 21, in <module>
    user = xee.get_user(token)
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/sdk.py", line 140, in get_user
    return xee_entities.parse_user(response), None
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/entities.py", line 166, in parse_user
    isodate.parse_datetime(user['birthDate']),
  File "/usr/local/lib/python2.7/dist-packages/isodate-0.5.4-py2.7.egg/isodate/isodatetime.py", line 51, in parse_datetime
    datestring, timestring = datetimestring.split('T')
AttributeError: 'NoneType' object has no attribute 'split'

Traceback (most recent call last):
  File "xee_exemple.py", line 21, in <module>
    user = xee.get_user(token)
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/sdk.py", line 140, in get_user
    return xee_entities.parse_user(response), None
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/entities.py", line 166, in parse_user
    isodate.parse_datetime(user['licenceDeliveryDate']),
KeyError: 'licenceDeliveryDate'

```

**Comment by qk7b** [comment]
You're right.

For the `nickname` part, there is an error in the official documentation of the API, I filled an issue about this (https://github.com/xee-lab/xee-api-docs/issues/38)

For the `birthDate` it seems there is an error with the parser.. I'll check that too.

For the `licenceDeliveryDate`, I made a typo, it's an `s` instead of a `c`. (This SDK needs more unit tests)

I'll do an update of the sdk soon to handle this :)

**Comment by tikismoke** [comment]
No problem, i'm here to help ;)

**Comment by qk7b** [comment]
Thanks :) I've just started working on it https://github.com/quentin7b/xee-sdk-python/pull/4

**Comment by tikismoke** [comment]
Ok solved the user parts.
Not try the other entitys as i have no car in my account for now and still the problem with get the token from tuple.

Nice job, don't forget to take advantage of your hollyday's too.
