### ISSUE TITLE
Exception in master Branch

### ISSUE THREAD

**Issue by tikismoke** [quentin7b/xee-sdk-python#9]
a problem with the get_status with accelerometer.

```
Traceback (most recent call last):
  File "xee_exemple.py", line 31, in <module>
    Status  ,error = xee.get_status(carID,token.access_token)
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.1-py2.7.egg/xee/sdk.py", line 217, in get_status
    return xee_entities.parse_status(response), None
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.1-py2.7.egg/xee/entities.py", line 309, in parse_status
    Accelerometer(accelerometer['x'], accelerometer['y'], accelerometer['z'],
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by tikismoke** [comment]
le pull request evite l'erreur, mais du coup get_status est vide :(

**Comment by tikismoke** [comment]
Works great, your a chief :)
